### ISSUE TITLE
Not able to Build the Editor

### ISSUE THREAD

**Issue by vinit-agr** [silentrob/superscript-editor#22]
Working with the latest version of node and npm, their is a problem while installing the dependencies for the project. Here is the Full log, Please let me know what is wrong. Thanks

```
superscript-editor$ npm install
npm WARN package.json superscript-editor@0.1.7 No repository field.
npm WARN package.json superscript-editor@0.1.7 No license field.
npm WARN engine stream-worker@0.0.1: wanted: {"node":"~0.10.0"} (current: {"node":"0.12.4","npm":"2.10.1"})

> kerberos@0.0.7 install /media/chat_ai/1/superscript-editor/node_modules/superscript/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
> bson@0.2.21 install /media/chat_ai/1/superscript-editor/node_modules/superscript/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> leveldown@0.10.5 install /media/chat_ai/1/superscript-editor/node_modules/superscript/node_modules/sfacts/node_modules/leveldown
> node-gyp rebuild

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-53-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/chat_ai/1/superscript-editor/node_modules/superscript/node_modules/sfacts/node_modules/leveldown
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

> leveldown@0.10.5 install /media/chat_ai/1/superscript-editor/node_modules/sfacts/node_modules/leveldown
> node-gyp rebuild

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-53-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/chat_ai/1/superscript-editor/node_modules/sfacts/node_modules/leveldown
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

> wndb-with-exceptions@3.0.1 postinstall /media/chat_ai/1/superscript-editor/node_modules/superscript/node_modules/lemmer/node_modules/wndb-with-exceptions
> node unpack.js WNdb-3.0.tar.gz


> WNdb@3.1.1 postinstall /media/chat_ai/1/superscript-editor/node_modules/sfacts/node_modules/WNdb
> node unpack.js WNdb-3.1.tar.gz

Extracting WNdb-3.1.tar.gz


> WNdb@3.1.1 postinstall /media/chat_ai/1/superscript-editor/node_modules/superscript/node_modules/WNdb
> node unpack.js WNdb-3.1.tar.gz

Extracting WNdb-3.1.tar.gz

npm ERR! Linux 3.13.0-53-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! leveldown@0.10.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@0.10.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/chat_ai/1/superscript-editor/npm-debug.log

```

**Comment by lucasfcosta** [comment]
Try using Node 0.10 instead of 0.12.
I've had the same problem as you, following the right instructions on the [node-gyp repository](https://github.com/TooTallNate/node-gyp) fixed it for me.

If you're using Unix this is what you've got to install:
- python (v2.7 recommended, v3.x.x is not supported)
- make
- A proper C/C++ compiler toolchain, like GCC

**Comment by silentrob** [comment]
Thanks for the feedback. I havn't tested the editor extensivly on linux, but everything seems to work okay on mac with node 0.12.x, and levelgraph should support 0.12 as well. Follow @lucasfcosta hints and if it continues to be an issue, we can open an issue on levelgraph.

**Comment by vinit-agr** [comment]
Thanks @lucasfcosta, i actually did reverted back to 0.10.25 and now its working fine.
@silentrob will try to run it with 0.12.x with proper node-gyp installation. if their is still a problem, will open another issue.

Thanks for your help.
