### ISSUE TITLE
Is it possible to import eliza.ss?

### ISSUE THREAD

**Issue by Rajan** [silentrob/superscript-editor#26]
I tried importing it and we're seeing this:

TypeError: Object #<Object> has no method 'importer'
    at postdata (/Users/rajanchandi/WebstormProjects/AI/superscript-editor/controllers/dashboard.js:73:16)
    at Layer.handle [as handle_request](/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/layer.js:95:5)
    at /Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/index.js:271:10)
    at /Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/view-helpers/index.js:69:5
    at Layer.handle [as handle_request](/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/index.js:312:13)
    at /Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/index.js:271:10)
    at /Users/rajanchandi/WebstormProjects/AI/superscript-editor/config/express.js:96:5
    at Layer.handle [as handle_request](/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/index.js:312:13)
    at /Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/index.js:271:10)
    at /Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/connect-flash/lib/flash.js:21:5
    at Layer.handle [as handle_request](/Users/rajanchandi/WebstormProjects/AI/superscript-editor/node_modules/express/lib/router/layer.js:95:5)

**Comment by Rajan** [comment]
I've been able to import this now.
