### ISSUE TITLE
cannot start on vagrant ubuntu 12

### ISSUE THREAD

**Issue by kyr7** [silentrob/superscript-editor#37]
vagrant@precise32:~/superscript-editor$ npm start  

> superscript-editor@0.1.7 start /home/vagrant/superscript-editor
> node app

/home/vagrant/superscript-editor/node_modules/mongodb/lib/mongodb/db.js:299
          throw err;
                ^
Error: Cannot find module '../../node_modules/ss-parser/lib/regexreply'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/home/vagrant/superscript-editor/node_modules/superscript/lib/topics/gambit.js:13:20)
    at module.exports (/home/vagrant/superscript-editor/node_modules/superscript/lib/topics/index.js:25:31)
    at NativeConnection.module.exports (/home/vagrant/superscript-editor/app.js:41:55)
    at NativeConnection.g (events.js:180:16)
    at NativeConnection.emit (events.js:92:17)
    at open (/home/vagrant/superscript-editor/node_modules/mongoose/lib/connection.js:453:10)
    at NativeConnection.Connection.onOpen (/home/vagrant/superscript-editor/node_modules/mongoose/lib/connection.js:462:5)
    at /home/vagrant/superscript-editor/node_modules/mongoose/lib/connection.js:421:10
    at /home/vagrant/superscript-editor/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:59:5
    at /home/vagrant/superscript-editor/node_modules/mongodb/lib/mongodb/db.js:296:11
    at process._tickCallback (node.js:448:13)

npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE
npm ERR! superscript-editor@0.1.7 start: `node app`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the superscript-editor@0.1.7 start script 'node app'.
npm ERR! This is most likely a problem with the superscript-editor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get their info via:
npm ERR!     npm owner ls superscript-editor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/superscript-editor/npm-debug.log

https://gist.github.com/kyr7/e15cc28aa058ef826682

**Comment by kyr7** [comment]
And this is how start fails for me on Ubuntu 14 VM:

Kirills-MacBook-Air:superscript-editor kirillskiy$ npm start

> superscript-editor@0.1.7 start /Users/kirillskiy/Documents/ubuntu14/superscript-editor
> node app

module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: dlopen(/Users/kirillskiy/Documents/ubuntu14/superscript-editor/node_modules/re2/build/Release/re2.node, 1): no suitable image found.  Did find:
	/Users/kirillskiy/Documents/ubuntu14/superscript-editor/node_modules/re2/build/Release/re2.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kirillskiy/Documents/ubuntu14/superscript-editor/node_modules/re2/re2.js:3:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kirillskiy/Documents/ubuntu14/superscript-editor/node_modules/node-normalizer/lib/normalizer.js:7:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/kirillskiy/.node/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE
npm ERR! superscript-editor@0.1.7 start: `node app`
npm ERR! Exit status 1
npm ERR!

**Comment by kyr7** [comment]
And this is how Ububtu 14 VM failure looks like:
events.js:72
        throw er; // Unhandled 'error' event
              ^
OpenError: IO error: testbot/MANIFEST-000001: Invalid argument
    at /vagrant/superscript-editor/node_modules/level-packager/node_modules/levelup/lib/levelup.js:114:34

npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE
npm ERR! superscript-editor@0.1.7 start: `node app`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the superscript-editor@0.1.7 start script 'node app'.
npm ERR! This is most likely a problem with the superscript-editor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get their info via:
npm ERR!     npm owner ls superscript-editor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/superscript-editor/npm-debug.log

**Comment by tzmartin** [comment]
I suspect this was an incomplete dependency installation.  Try running `npm install` again within the `/home/vagrant/superscript-editor/node_modules/superscript/`
